// Generated by CoffeeScript 1.12.7
(function() {
  var Base, Moment, base62, crypto, dic64;

  Base = require('base-p');

  base62 = new Base(62);

  Moment = require('moment');

  this.time = function(date) {
    var unixstamp;
    unixstamp = date != null ? Moment(date).unix() : Moment().unix();
    return base62.encode(Math.floor(unixstamp / 6));
  };

  crypto = require('crypto');

  dic64 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz._';

  this.uniqueness = function() {
    var p, r;
    r = crypto.randomBytes(3);
    p = ((r[0] >> 6) << 0) + ((r[1] >> 6) << 2) + ((r[2] >> 6) << 4);
    return [dic64[r[0] & 63], dic64[r[1] & 63], dic64[r[2] & 63], dic64[p]].join('');
  };

}).call(this);
